name: Build and Release MCDR Plugin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get metadata
        id: meta
        run: |
          JSON_VERSION=$(jq -r '.version' mcdreforged.plugin.json)
          NAME=$(jq -r '.name' mcdreforged.plugin.json)
          echo "version=$JSON_VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$JSON_VERSION" >> $GITHUB_OUTPUT
          echo "name=$NAME" >> $GITHUB_OUTPUT
          echo "filename=${NAME}-${JSON_VERSION}.mcdr" >> $GITHUB_OUTPUT

      - name: Build MCDR Plugin
        run: |
          zip -r ${{ steps.meta.outputs.filename }} smptoolkit/ mcdreforged.plugin.json LICENSE README.md

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.meta.outputs.tag }}
          body_path: release.md
          files: ${{ steps.meta.outputs.filename }}
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
